name: Bug report
description: Create a report to help us improve DJINN
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Commands to run to reproduce the issue.
      placeholder: |
        1. djinn "..."
        2. error...
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      items:
        - 2.1.x
        - 2.0.x
        - 1.x
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      items:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
